name: Upload coverage reports to Codecov
on:
  push:
    branches: ["5-stable"]
  pull_request:
    branches: ["5-stable"]
jobs:
  codecov:
    runs-on: ubuntu-latest
    container: ruby:latest
    steps:
      - name: Checkout the repository(CRuby)
        uses: actions/checkout@v4
      - name: Setup CRuby
        uses: ruby/setup-ruby@v1
      - name: Install minitest
        run: gem install minitest -v 5.15.0
      - name: Install oj
        run: gem install oj -v 3.10.0
      - name: Install bundle, rake, simplecov, and simplecov-cobertura
        run: gem install bundle rake simplecov simplecov-cobertura
      - name: Create test/test_helper.rb
        run: /bin/cp cov-test-helper ./test/test_helper.rb
      - name: Create a directory for the coverage
        run: mkdir -p tmp/coverage
      - name: Check the CRuby version
        run: ruby -v
      - name: Execute public tests
        run: rake publictest
      - name: Run Codecov on GitHub Actions
        uses: codecov/codecov-action@v4.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tmp/coverage/coverage.xml
          verbose: true

