name: rake test
on:
  push:
    branches: ["5-stable"]
  pull_request:
    branches: ["5-stable"]
jobs:
  test-cruby:
    name: rake test with CRuby ${{ matrix.cruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cruby: ["2.4", "3.3"]
    steps:
      - name: Checkout the repository(CRuby)
        uses: actions/checkout@v4
      - name: Setup CRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.cruby }}
      - name: Install minitest
        run: gem install minitest -v 5.15.0
      - name: Install oj
        run: gem install oj -v 3.10.0
      - name: Install bundle and rake
        run: gem install bundle rake
      - name: Cache the dependent gems
        uses: actions/cache@v2
        with:
          path: ./cache
          key: ${{ runner.os }}-ruby-${{ matrix.cruby }}-${{ hashFiles('./gem.snapshot') }}
      - name: Check the CRuby version
        run: ruby -v
      - name: Execute public tests
        run: rake publictest
  test-jruby:
    name: rake test with JRuby ${{ matrix.jruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jruby: ["jruby-9.2", "jruby-9.4"]
    steps:
      - name: Checkout the repository(JRuby)
        uses: actions/checkout@v2
      - name: Setup JRuby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.jruby }}
      - name: Install minitest
        run: gem install minitest -v 5.15.0
      - name: Install bundle, rake, and jrjackson
        run: gem install bundle rake jrjackson
      - name: Cache the dependent gems
        uses: actions/cache@v2
        with:
          path: ./cache
          key: ${{ runner.os }}-ruby-${{ matrix.jruby }}-${{ hashFiles('./gem.snapshot') }}
      - name: Check the JRuby version
        run: jruby -v
      - name: Execute public tests
        run: rake publictest

